# configuration for develop and master branch

-
  branches:
    only:
      - master
      - develop

  skip_tags: true
  image: Visual Studio 2019
  configuration: Release
  test: off

  pull_requests:
    do_not_increment_build_number: false

  install:
    # Install dotnet core 3.0 latest
    - cinst dotnetcore-sdk

  build_script:
    - ps: .\build.ps1 CI

  artifacts:
    - path: \output\*.msi
    - path: \output\*.nupkg
    - path: \output\*.zip

  nuget:
    disable_publish_on_pr: true

  skip_commits:
    files:
      - '**/*.md'