# configuration for develop and master branch

-
  branches:
    only:
      - master
      - develop

  skip_tags: true
  image: Visual Studio 2017
  configuration: Release
  platform: Mixed Platforms
  test: off

  pull_requests:
    do_not_increment_build_number: false

  # Install dotnet core 3.0 latest (alpha!!), as this is not provided on AppVeyor yet
  install:
    - ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe'
    - ps: Start-Process .\dotnet-sdk-latest-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait

  build_script:
    - ps: .\build.ps1 -Package -Verbose

  artifacts:
    - path: \build\publish\*.*

  nuget:
    disable_publish_on_pr: true

  skip_commits:
    files:
      - '**/*.md'